### ISSUE TITLE
Doesn't play well with some HTML items

### ISSUE THREAD

**Issue by kajzersoze** [mate-desktop/mate-notification-daemon#106]
I've noticed this only with Mate notification daemon.
Some html elements are not displayed right.
But this one is even more disturbing.. if there's a & char in the string for notification , notification for body will just be empty.
To test run this in terminal :
`notify-send "test & example"`

It will turn that to a empty string.

**Comment by monsta** [comment]
Fix applied in https://github.com/mate-desktop/mate-notification-daemon/commit/f95d699d693d3781a15c90a04bc63ad62897eb48.
