### ISSUE TITLE
Can't handle image paths containing spaces [$10]

### ISSUE THREAD

**Issue by lazka** [mate-desktop/mate-notification-daemon#117]
Sending a notification (with app_icon, image_path and image-path all set to the same uri) with a file URI for an image, derived from a path containing spaces fails to load.

e.g. "file:///somepath/my%20image.png" results in mate-notification-daemon trying to load "/somepath/my%20image.png" while it should be "/somepath/my image.png". At least this is what I see using strace.

I've tested this on Ubuntu 16.10 which has version "1.16.0-1"

**Comment by monsta** [comment]
The fix is now released in version 1.18.1.
