### ISSUE TITLE
no popups visible on ubuntu 18.04

### ISSUE THREAD

**Issue by tecan** [mate-desktop/mate-notification-daemon#135]
#### Expected behaviour
would normally see a popup somewhere

#### Actual behaviour
if i try preview with       mate-notification-properties   i see no popups
or try notify-send from command line i see nothing

#### Linux Distribution
ubuntu 18.04

**Comment by lukefromdc** [comment]
Is this with a new install of Ubuntu or after a round of updates?

**Comment by tecan** [comment]
gnome-session-inhibit is the cause

**Comment by lukefromdc** [comment]
Do you mean commandline mate-session-inhibit (or gnome-session-inhibit) and not the panel inhibit applet?

I just found that the inhibit applet on the panel does not cause any problems with notifications whether toggled on or off on my system. I have MATE 1.21 from git master on Debian Unstable with locally built GTK 3.23.1 and GLIB 2.57.1.

**Comment by tecan** [comment]
yes "mate-session-inhibit --inhibit suspend gedit"  or any of the --inhibit params do it aswell

**Comment by lukefromdc** [comment]
I just ran "mate-session-inhibit --inhibit suspend gedit" and gedit came up fine, then opened mate-control-center and previewed the popup notifications. On my system, they still worked fine. Wonder what is different-one or more underlying libs maybe?

**Comment by tecan** [comment]
hmmm, not sure why but its working good for me now too, maybe i had other instance running. thanks again for the help.
