### ISSUE TITLE
mate-notification-daemon-1.16.1-1.el7 crashes Scientific Linux 7

### ISSUE THREAD

**Issue by mahmacc** [mate-desktop/mate-notification-daemon#136]
#### Expected behaviour
To show icons and notifications

#### Actual behaviour
Icons for Emacs and Firefox in task bar show only
as a small rectangle plus border. The icon for
the wireless link shows as a pair of 'No entry' signs.
More importantly, when changing window using the
touchscreen, the system quite often crashes and
restarts, losing the work in progress

#### Steps to reproduce the behaviour
I have seen this several times now since updating
mate-notification-daemon from the copy in the epel
repository but I have not yet found a clear enough
pattern to be able to reproduce it to order.

#### MATE general version
1.16.2

#### Package version
See subject line

#### Linux Distribution
Scientific Linux 7x

#### Link to downstream report of your Distribution
Not sure what this means.

**Comment by raveit65** [comment]
Code for Notification-area-applet isn't from mate-notification-daemon.

> Link to downstream report of your Distribution

> Not sure what this means.

This means to file out a report against your own distro first, to give your distro maintainer a chance to verify if this is an distro-specific issue or not.

**Comment by mahmacc** [comment]
Thanks, raveit. It seems I've fallen foul of a common problem in modern Linux,
namely that it's hard for even moderately well-informed users to identify
where in a set of software the error is. It is strange that the phenomena  first appeared at the same time.

However, the symptom I want to get fixed is the crashing. This now seems to happen
mainly when i try to use window switcher via the touch screen to move to the 7th
(of 8) windows. (That window has just a terminal in it). The reason for associating this with the notification-daemon is that the crash is followed by an immediate restart, and about one time in 3 there is then a little dialog box saying a problem has arisen with mate-notification-daemon....and asking whether to report (which I have on a couple of occasions: no idea where the report goes. to the distro?)

**Comment by raveit65** [comment]
Sorry we can't move reports to mate-panel, the place of notification-area-applet.
This is the wrong repo here.

As fedora maintainer i am not sure if i ever will update epel7 repo, because any update to mate-1-20 means a switch to gtk3.
Honestly, i don't have any time or motivation any more to maintain MATE (unpaid) in my free time for a non-free distro (rhel7) and his derivates.
**MAINTAINER IS WANTED !**

I suggest to use fedora if you want use an updated MATE.
