### ISSUE TITLE
Memory leak of setting value in notification_properties_position_notify

### ISSUE THREAD

**Issue by jranieri-grammatech** [mate-desktop/mate-notification-daemon#147]
The value returned by `g_settings_get_string` here is leaked every time it is is called:
https://github.com/mate-desktop/mate-notification-daemon/blob/e143ad579dc1d22101260843ee51d52ba3ce8626/src/capplet/mate-notification-properties.c#L82

This problem was found using the static analysis tool GrammaTech CodeSonar.

**Comment by raveit65** [comment]
PR is welcome.
