### ISSUE TITLE
Add a menu item to toggle "do-not-disturb"

### ISSUE THREAD

**Issue by kbsali** [mate-desktop/mate-notification-daemon#166]
Feature request : add a menu item to toggle "do-not-disturb" instead of having to do this through the settings window.

#### Expected behaviour

Very often when I'm at work I want to easily & quickly toggle the "do-not-disturb" feature.

#### Actual behaviour

To do so today, I have to click on the "Settings..." item of the applet to open up the "Indicator Notificatino Settings" windows and then check the "Enable do not disturb" checkbox.

#### MATE general version

1.22

#### Package version

1.22.1-0ubuntu1

#### Linux Distribution

Ubuntu-Mate 19.10

**Comment by raveit65** [comment]
Yeah, a little applet would be nice which would toogle the state
For the moment you can add 2 user-defined panel launcher from add-to-panel-menu
One with this command
`gsettings set org.mate.NotificationDaemon do-not-disturb true`
And another with
`gsettings set org.mate.NotificationDaemon do-not-disturb false`
Works fine here.

**Comment by kbsali** [comment]
thanks for the tips, I did not have the full command in mind yet! :)
I have added those 2 launchers, but the bell icon indicator won't update (when enabling "do not disturb" from the settings window, the icon show a "Z"). Is that normal? Any work around ?
thanks for you help!

**Comment by trism** [comment]
indicator-notifications uses a different settings key for do-not-disturb:
`gsettings set net.launchpad.indicator.notifications do-not-disturb true`
(which is the app showing the bell icon in ubuntu mate)

**Comment by kbsali** [comment]
thanks @trism.
So executing this in a terminal works as expected
`gsettings set org.mate.NotificationDaemon do-not-disturb false && gsettings set net.launchpad.indicator.notifications do-not-disturb false`
`gsettings set org.mate.NotificationDaemon do-not-disturb true && gsettings set net.launchpad.indicator.notifications do-not-disturb true`

But when pasting those commands in custom launchers it won't do anything (see screenshot)... 

![2020-02-27_18-57](https://user-images.githubusercontent.com/53676/75472005-3277d480-5993-11ea-81c8-09de8e218e26.png)

What am I doing wrong?

**Comment by raveit65** [comment]
I am using type application and not application in terminal with the single command `gsettings set org.mate.NotificationDaemon do-not-disturb true`

**Comment by trism** [comment]
Settings the net.launchpad.indicator.notifications do-not-disturb key will set the org.mate.NotificationDaemon do-not-disturb key when indicator-notifications is running, so you don't need both. There is a separate key because indicator-notifications doesn't only run on mate.

**Comment by kbsali** [comment]
perfect, switched to `Application` and `net.launchpad.indicator.notifications do-not-disturb` only,
it fixes the issue.

The toggle menu item would still make it even easier! :)
