### ISSUE TITLE
Notification Area - Qlipper 

### ISSUE THREAD

**Issue by mexsudo** [mate-desktop/mate-notification-daemon#169]
#### Expected behaviour
add "qlipper" command to startup applications
shutdown, reboot.
qlipper in the Notification Area

#### Actual behaviour
no Icon in the Notification Area
---
terminal
$ qlipper
An instance of qlipper is already running!

#### Steps to reproduce the behaviour
add "qlipper" command to startup applications
shutdown, reboot.

#### MATE general version
1.20.4

#### Package version
1.20.4-2

#### Linux Distribution
Debian 10 buster

*** note: Debian Testing and Sid do not have this issue... it works as expected

**Comment by rbuj** [comment]
I recognize that Qlipper is a great clipboard manager for desktop environments based on Qt, such as LXQt, but I recommend you to use a GTK+ clipboard manager on MATE, such as [ClipIt](https://github.com/CristianHenzel/ClipIt).
