### ISSUE TITLE
Starting thunderbird freeze whole MATE Desktop and apps for 30 seconds

### ISSUE THREAD

**Issue by jean2** [mate-desktop/mate-notification-daemon#174]
#### Expected behaviour

No freeze, responsive desktop and apps.

#### Actual behaviour

When I start Thunderbird to read my e-mail, the whole dektop freeze for something like 30 seconds. I can't use Thunderbird, I can't use firefox, I can't use MATE menus, etc. Those apps don't even refresh if I move them. I know it's MATE because the mouse still work and I can switch to a text console that is not frozen. After a while, it unfreezes and things go back to normal.

#### Steps to reproduce the behaviour

Debian 10. Install MATE + KDE/Plasma.

#### MATE general version

MATE 1.20.4 on Debian 10. Most likely applies to other versions and other distro.

#### Package version

Debian package 1.20.4-2

#### Linux Distribution

Debian 10.3

#### Link to downstream report of your Distribution

None

#### Workaround

root# cd /usr/share/dbus-1/services/
root# mv org.kde.knotify.service org.kde.knotify.service-disabled
root# mv org.kde.plasma.Notifications.service org.kde.plasma.Notifications.service-disabled

If I do the above, there is no freeze at all, it fully solve the issue.
Note that I should not have to cripple KDE/Plasma to get MATE working properly. People using KDE on my computer (that would be me ;-) won't be pleased.

#### Full analysis

MATE notification system is not compatible with other desktops :

https://bugzilla.redhat.com/show_bug.cgi?id=1490959

Thunderbird attempts to notify about received e-mails, and that cause the Desktop and app freeze.

**Comment by raveit65** [comment]
Will be fixed with https://github.com/mate-desktop/mate-notification-daemon/pull/214
