### ISSUE TITLE
Daemon crash

### ISSUE THREAD

**Issue by ghost** [mate-desktop/mate-notification-daemon#180]
I'm a newbie to Linux world. I've found crash reports. I'm not aware if it interrupt the normal functioning of my system. Would like to share this issue for further development to avoid possible crashes. I'm pasting the issue below. please help me.
#### Actual behaviour
===================================================================
 Info                                                              
===================================================================
           PID: 1621 (mate-notificati)
           UID: 1000 (user)
           GID: 1000 (user)
        Signal: 11 (SEGV)
     Timestamp: Wed 2020-09-02 09:15:39 IST (1 day 9h ago)
  Command Line: /usr/lib/mate-notification-daemon/mate-notification-daemon
    Executable: /usr/lib/mate-notification-daemon/mate-notification-daemon
 Control Group: /user.slice/user-1000.slice/user@1000.service/dbus.service
          Unit: user@1000.service
     User Unit: dbus.service
         Slice: user-1000.slice
     Owner UID: 1000 (user)
       Boot ID: 570b44c0febd4c7ebfa05134c0798ff3
    Machine ID: fede3597f8724a62b7726a319d60a6bc
      Hostname: HP
       Storage: /var/lib/systemd/coredump/core.mate-notificati.1000.570b44c0febd4c7ebfa05134c0798ff3.1621.1599018339000000.lz4
       Message: Process 1621 (mate-notificati) of user 1000 dumped core.
                
                Stack trace of thread 1621:
                #0  0x00007fafc8318b10 n/a (libgdk-3.so.0)
                #1  0x00007fafc8318c54 n/a (libgdk-3.so.0)
                #2  0x00007fafc82ebb3f n/a (libgdk-3.so.0)
                #3  0x00007fafc8ee3801 n/a (libwnck-3.so.0)
                #4  0x00007fafc8ee38e2 n/a (libwnck-3.so.0)
                #5  0x00007fafc8edab7f n/a (libwnck-3.so.0)
                #6  0x00007fafc8ecdc11 n/a (libwnck-3.so.0)
                #7  0x00005583392e6ec5 n/a (mate-notification-daemon)
                #8  0x00007fafc25e8dae ffi_call_unix64 (libffi.so.6)
                #9  0x00007fafc25e871f ffi_call (libffi.so.6)
                #10 0x00007fafc7ab2901 g_cclosure_marshal_generic (libgobject-2.0.so.0)
                #11 0x00007fafc7ab210d g_closure_invoke (libgobject-2.0.so.0)
                #12 0x00007fafc7ac505e n/a (libgobject-2.0.so.0)
                #13 0x00007fafc7accc80 g_signal_emitv (libgobject-2.0.so.0)
                #14 0x00005583392e4af9 n/a (mate-notification-daemon)
                #15 0x00007fafc7dcd8f7 n/a (libgio-2.0.so.0)
                #16 0x00007fafc7db58fc n/a (libgio-2.0.so.0)
                #17 0x00007fafc77d7285 g_main_context_dispatch (libglib-2.0.so.0)
                #18 0x00007fafc77d7650 n/a (libglib-2.0.so.0)
                #19 0x00007fafc77d7962 g_main_loop_run (libglib-2.0.so.0)
                #20 0x00007fafc87dea25 gtk_main (libgtk-3.so.0)
                #21 0x00005583392e2fcb main (mate-notification-daemon)
                #22 0x00007fafc7083b97 __libc_start_main (libc.so.6)
                #23 0x00005583392e306a _start (mate-notification-daemon)
                
                Stack trace of thread 1623:
                #0  0x00007fafc7176cf9 __GI___poll (libc.so.6)
                #1  0x00007fafc77d75c9 n/a (libglib-2.0.so.0)
                #2  0x00007fafc77d76dc g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007fafc77d7721 n/a (libglib-2.0.so.0)
                #4  0x00007fafc77ff175 n/a (libglib-2.0.so.0)
                #5  0x00007fafc6a346db start_thread (libpthread.so.0)
                #6  0x00007fafc7183a3f __clone (libc.so.6)
                
                Stack trace of thread 1624:
                #0  0x00007fafc717d959 syscall (libc.so.6)
                #1  0x00007fafc781d87a g_cond_wait_until (libglib-2.0.so.0)
                #2  0x00007fafc77aa571 n/a (libglib-2.0.so.0)
                #3  0x00007fafc77ffb14 n/a (libglib-2.0.so.0)
                #4  0x00007fafc77ff175 n/a (libglib-2.0.so.0)
                #5  0x00007fafc6a346db start_thread (libpthread.so.0)
                #6  0x00007fafc7183a3f __clone (libc.so.6)
                
                Stack trace of thread 1625:
                #0  0x00007fafc7176cf9 __GI___poll (libc.so.6)
                #1  0x00007fafc77d75c9 n/a (libglib-2.0.so.0)
                #2  0x00007fafc77d7962 g_main_loop_run (libglib-2.0.so.0)
                #3  0x00007fafc7dc5276 n/a (libgio-2.0.so.0)
                #4  0x00007fafc77ff175 n/a (libglib-2.0.so.0)
                #5  0x00007fafc6a346db start_thread (libpthread.so.0)
                #6  0x00007fafc7183a3f __clone (libc.so.6)
                
                Stack trace of thread 1622:
                #0  0x00007fafc7176cf9 __GI___poll (libc.so.6)
                #1  0x00007fafc77d75c9 n/a (libglib-2.0.so.0)
                #2  0x00007fafc77d76dc g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007fafbdc7236d n/a (libdconfsettings.so)
                #4  0x00007fafc77ff175 n/a (libglib-2.0.so.0)
                #5  0x00007fafc6a346db start_thread (libpthread.so.0)
                #6  0x00007fafc7183a3f __clone (libc.so.6)
===================================================================
 GDB Log                                                           
===================================================================

warning: core file may not match specified executable file.
[New LWP 1621]
[New LWP 1623]
[New LWP 1624]
[New LWP 1625]
[New LWP 1622]

warning: Unexpected size of section `.reg-xstate/1621' in core file.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/mate-notification-daemon/mate-notification-daemon'.
Program terminated with signal SIGSEGV, Segmentation fault.

warning: Unexpected size of section `.reg-xstate/1621' in core file.
#0  0x00007fafc8318b10 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
[Current thread is 1 (Thread 0x7fafc96e5f00 (LWP 1621))]

===================================================================
 GDB Backtrace                                                     
===================================================================

warning: core file may not match specified executable file.
[New LWP 1621]
[New LWP 1623]
[New LWP 1624]
[New LWP 1625]
[New LWP 1622]

warning: Unexpected size of section `.reg-xstate/1621' in core file.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/mate-notification-daemon/mate-notification-daemon'.
Program terminated with signal SIGSEGV, Segmentation fault.

warning: Unexpected size of section `.reg-xstate/1621' in core file.
#0  0x00007fafc8318b10 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
[Current thread is 1 (Thread 0x7fafc96e5f00 (LWP 1621))]
#0  0x00007fafc8318b10 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#1  0x00007fafc8318c54 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#2  0x00007fafc82ebb3f in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#3  0x00007fafc8ee3801 in ?? () from /usr/lib/x86_64-linux-gnu/libwnck-3.so.0
#4  0x00007fafc8ee38e2 in ?? () from /usr/lib/x86_64-linux-gnu/libwnck-3.so.0
#5  0x00007fafc8edab7f in ?? () from /usr/lib/x86_64-linux-gnu/libwnck-3.so.0
#6  0x00007fafc8ecdc11 in ?? () from /usr/lib/x86_64-linux-gnu/libwnck-3.so.0
#7  0x00005583392e6ec5 in ?? ()
#8  0x00007fafc25e8dae in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#9  0x00007fafc25e871f in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#10 0x00007fafc7ab2901 in g_cclosure_marshal_generic () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007fafc7ab210d in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007fafc7ac505e in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007fafc7accc80 in g_signal_emitv () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00005583392e4af9 in ?? ()
#15 0x00007fafc7dcd8f7 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#16 0x00007fafc7db58fc in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#17 0x00007fafc77d7285 in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007fafc77d7650 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007fafc77d7962 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007fafc87dea25 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#21 0x00005583392e2fcb in main ()

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================

warning: core file may not match specified executable file.
[New LWP 1621]
[New LWP 1623]
[New LWP 1624]
[New LWP 1625]
[New LWP 1622]

warning: Unexpected size of section `.reg-xstate/1621' in core file.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/mate-notification-daemon/mate-notification-daemon'.
Program terminated with signal SIGSEGV, Segmentation fault.

warning: Unexpected size of section `.reg-xstate/1621' in core file.
#0  0x00007fafc8318b10 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
[Current thread is 1 (Thread 0x7fafc96e5f00 (LWP 1621))]
warning: Unexpected size of section `.reg-xstate/1622' in core file.

Thread 5 (Thread 0x7fafbdc6a700 (LWP 1622)):
#0  0x00007fafc7176cf9 in __GI___poll (fds=0x55833ab96c00, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007fafc77d75c9 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007fafc77d76dc in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007fafbdc7236d in ?? () from /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
No symbol table info available.
#4  0x00007fafc77ff175 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007fafc6a346db in start_thread (arg=0x7fafbdc6a700) at pthread_create.c:463
        pd = 0x7fafbdc6a700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140392779917056, -7507106883507133350, 140392779914368, 0, 94022113967344, 140732546133568, 7533991788431467610, 7534217984876667994}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007fafc7183a3f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.
warning: Unexpected size of section `.reg-xstate/1625' in core file.

Thread 4 (Thread 0x7fafaffff700 (LWP 1625)):
#0  0x00007fafc7176cf9 in __GI___poll (fds=0x7fafb801afe0, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007fafc77d75c9 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007fafc77d7962 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007fafc7dc5276 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#4  0x00007fafc77ff175 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007fafc6a346db in start_thread (arg=0x7fafaffff700) at pthread_create.c:463
        pd = 0x7fafaffff700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140392548792064, -7507106883507133350, 140392548789376, 0, 94022113967904, 140392779913344, 7534022927481234522, 7534217984876667994}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007fafc7183a3f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.
warning: Unexpected size of section `.reg-xstate/1624' in core file.

Thread 3 (Thread 0x7fafbcc68700 (LWP 1624)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
No locals.
#1  0x00007fafc781d87a in g_cond_wait_until () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007fafc77aa571 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007fafc77ffb14 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007fafc77ff175 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007fafc6a346db in start_thread (arg=0x7fafbcc68700) at pthread_create.c:463
        pd = 0x7fafbcc68700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140392763131648, -7507106883507133350, 140392763128960, 0, 94022113967504, 140732546134656, 7533993984233497690, 7534217984876667994}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007fafc7183a3f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.
warning: Unexpected size of section `.reg-xstate/1623' in core file.

Thread 2 (Thread 0x7fafbd469700 (LWP 1623)):
#0  0x00007fafc7176cf9 in __GI___poll (fds=0x7fafb8007cb0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007fafc77d75c9 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007fafc77d76dc in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007fafc77d7721 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007fafc77ff175 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007fafc6a346db in start_thread (arg=0x7fafbd469700) at pthread_create.c:463
        pd = 0x7fafbd469700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140392771524352, -7507106883507133350, 140392771521664, 0, 94022113967744, 140392779912960, 7533990688382968922, 7534217984876667994}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007fafc7183a3f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 1 (Thread 0x7fafc96e5f00 (LWP 1621)):
#0  0x00007fafc8318b10 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
No symbol table info available.
#1  0x00007fafc8318c54 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
No symbol table info available.
#2  0x00007fafc82ebb3f in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
No symbol table info available.
#3  0x00007fafc8ee3801 in ?? () from /usr/lib/x86_64-linux-gnu/libwnck-3.so.0
No symbol table info available.
#4  0x00007fafc8ee38e2 in ?? () from /usr/lib/x86_64-linux-gnu/libwnck-3.so.0
No symbol table info available.
#5  0x00007fafc8edab7f in ?? () from /usr/lib/x86_64-linux-gnu/libwnck-3.so.0
No symbol table info available.
#6  0x00007fafc8ecdc11 in ?? () from /usr/lib/x86_64-linux-gnu/libwnck-3.so.0
No symbol table info available.
#7  0x00005583392e6ec5 in ?? ()
No symbol table info available.
#8  0x00007fafc25e8dae in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
No symbol table info available.
#9  0x00007fafc25e871f in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
No symbol table info available.
#10 0x00007fafc7ab2901 in g_cclosure_marshal_generic () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#11 0x00007fafc7ab210d in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#12 0x00007fafc7ac505e in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#13 0x00007fafc7accc80 in g_signal_emitv () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#14 0x00005583392e4af9 in ?? ()
No symbol table info available.
#15 0x00007fafc7dcd8f7 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#16 0x00007fafc7db58fc in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#17 0x00007fafc77d7285 in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#18 0x00007fafc77d7650 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#19 0x00007fafc77d7962 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#20 0x00007fafc87dea25 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#21 0x00005583392e2fcb in main ()
No symbol table info available.
#0  0x00007fafc8318b10 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#1  0x00007fafc8318c54 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#2  0x00007fafc82ebb3f in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#3  0x00007fafc8ee3801 in ?? () from /usr/lib/x86_64-linux-gnu/libwnck-3.so.0
#4  0x00007fafc8ee38e2 in ?? () from /usr/lib/x86_64-linux-gnu/libwnck-3.so.0
#5  0x00007fafc8edab7f in ?? () from /usr/lib/x86_64-linux-gnu/libwnck-3.so.0
#6  0x00007fafc8ecdc11 in ?? () from /usr/lib/x86_64-linux-gnu/libwnck-3.so.0
#7  0x00005583392e6ec5 in ?? ()
#8  0x00007fafc25e8dae in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#9  0x00007fafc25e871f in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#10 0x00007fafc7ab2901 in g_cclosure_marshal_generic () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007fafc7ab210d in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007fafc7ac505e in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007fafc7accc80 in g_signal_emitv () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00005583392e4af9 in ?? ()
#15 0x00007fafc7dcd8f7 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#16 0x00007fafc7db58fc in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#17 0x00007fafc77d7285 in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007fafc77d7650 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007fafc77d7962 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007fafc87dea25 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#21 0x00005583392e2fcb in main ()

**Comment by raveit65** [comment]
Please quote posting with hash numbers (#...). You have linked your posting with a lot of reports.
Thanks for that....

**Comment by raveit65** [comment]
User is a ghost, closing.
