### ISSUE TITLE
Different icon-size for buttons

### ISSUE THREAD

**Issue by luigifab** [mate-desktop/mate-notification-daemon#197]
Can you set `icon-size` of _Preview_ button to 4 (like the _Close_ button)?

#### Expected behaviour (GTK 3.24)

![image](https://user-images.githubusercontent.com/31816829/117701658-c9f7ca80-b1c7-11eb-9cc5-b5c989b1f6d0.png)

#### Actual behaviour (GTK 3.24)

![image](https://user-images.githubusercontent.com/31816829/117701608-bb111800-b1c7-11eb-8411-e815dde11d12.png)

#### "Original" behaviour (GTK 2.24)

![mate-notification-properties](https://user-images.githubusercontent.com/31816829/120035800-6eb73c00-bfff-11eb-9c1e-b706227422f1.png)

#### Steps to reproduce the behaviour

Run `mate-notification-properties`.

#### MATE general version

1.24.1

#### Package version

1.24.1-1 (http://ftp2.fr.debian.org/debian/pool/main/m/mate-notification-daemon/mate-notification-daemon_1.24.1-1_amd64.deb)

#### Linux Distribution

Debian Testing

**Comment by lukefromdc** [comment]
With git master 1.25 versions of the mate packages on Debian Unstable, those buttons came up the same size in every theme I have. Checked with gtk inspector and the button icon areas as well as the icons inside were the same. Now we need to find out what is different here

**Comment by luigifab** [comment]
Yes, fixed with Mate 1.26:

![image](https://user-images.githubusercontent.com/31816829/148192173-3a99f61c-35b3-4d21-bfac-d05cba6f6f34.png)
