### ISSUE TITLE
Pop up notifications cause apps to grey out and become unresponsive

### ISSUE THREAD

**Issue by tharris104** [mate-desktop/mate-notification-daemon#198]
#### Actual behaviour
Any application that tries to notifiy will grey out the app and become unresponsive. 

#### Steps to reproduce the behaviour
Control Center -> Popup Notifications -> Preview
or:
$ time notify-send lalala
real	0m50.055s
user	0m0.006s
sys	0m0.002s

#### MATE general version
1.24.1

#### Package version
mate-notification-daemon-1.24.2-1.fc34.x86_64

#### Linux Distribution
Fedora release 34 (Thirty Four)

#### Link to bugreport of your Distribution (requirement)
https://unix.stackexchange.com/questions/572157/mate-notification-daemon-stopping-mate-notifications-timeout

**Comment by raveit65** [comment]
I can't reproduce a `grey-out` of applications in an updated f34.
```
[rave@f34-test ~]$ time notify-send lalla

real	0m0,102s
user	0m0,004s
sys	0m0,004s
[rave@f34-test ~]$ 
```
Same with using the preview from `mate-notification-properties`.
Or any other application which will send notification.
Any chance that another notification daemon from another DE, eg. kde,etc., is istalled and cause problems?

**Comment by tharris104** [comment]
Well, after looking again just now, I've found a way to keep this from crashing

$ /usr/libexec/mate-notification-daemon -r
Gtk-Message: 08:49:09.764: Failed to load module "colorreload-gtk-module"

So I installed this

$ sudo dnf install kde-gtk-config

and used the suggestion from the other link, and it works now with no timeouts.

$ sudo cp /usr/lib64/gtk-3.0/modules/libcolorreload-gtk-module.so /usr/lib/gtk-3.0/modules/

Thanks for the quick response, maybe this helps someone else.

**Comment by tharris104** [comment]
I had started out saying no, no other DE are installed. Also, I had this happen on 2 different PC's going from F30 -> F34. One of them I did in single increments, the other was F30 -> F32 -> F34.

**Comment by tharris104** [comment]
I responded a bit too quick.. here is more info.. because now that the notification works, it sends the application into a loop of "Resource temporarily unavailable" errors until it finally just quits. Attached strace:

$ strace /usr/libexec/mate-notification-daemon -r --debug

[strace-mate-notification-daemon.txt](https://github.com/mate-desktop/mate-notification-daemon/files/6501574/strace-mate-notification-daemon.txt)

**Comment by raveit65** [comment]
> /usr/lib64/gtk-3.0/modules/libcolorreload-gtk-module.so

But Mate with a normal installation doesn't need something from kde.
So the question is what component from KDE is installed, maybe a theme?
Can you please check if kde notification daemon is installed?

**Comment by tharris104** [comment]
Yes, thats exactly what it was. I found some plasma packages and with them removed now, notifications are working again. Thank you for the help!
