### ISSUE TITLE
Building do.not-disturb applet in-process breaks translations in panel main menu

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/mate-notification-daemon#219]
#### Expected behaviour

working translation of panel main menu
#### Actual behaviour
Lock screen, log out and shutdown

#### Steps to reproduce the behaviour
use --enable-in-process build flag

#### MATE general version
> 1.27.0

#### Package version

> 1.27.0
#### Linux Distribution
fedora, probably all

#### Link to bugreport of your Distribution (requirement)
not released yet

This is the weirdest shit ever! Tested with German, French and Spanish language.
Building applet out-of-process brings back the translated menu entries.
![main_menu_untranslated](https://github.com/mate-desktop/mate-notification-daemon/assets/961604/23e50201-7b1d-4985-ae2a-9041cad1919d)

Mate-media package has the same issue.
Package are not ready for distribution.

**Comment by raveit65** [comment]
@mate-desktop/core-team 
Please try to reproduce the issue in your language.

**Comment by lukefromdc** [comment]
Same as mate-media, I have NO working knowledge of how translations work and no ability to check them as I do not understand any other languages. If someone else can't fix this, wayland compatable builds become an exotic, user-built only option for a few.
