### ISSUE TITLE
mate-notification-daemon crash in archlinux & i3wm 

### ISSUE THREAD

**Issue by mesina** [mate-desktop/mate-notification-daemon#40]
When I start notification-daemon in an i3wm on archlinux and try to send a notification via notifiy-send mate-notification-daemon crashes  with the following message in terminal:

```
(mate-notification-daemon:20501): Wnck-CRITICAL **: wnck_window_is_on_workspace: assertion 'WNCK_IS_WORKSPACE (workspace)' failed
[1]    20501 trace trap (core dumped)  /usr/lib/mate-notification-daemon/mate-notification-daemon
```

**Comment by monsta** [comment]
@flexiondotorg: looks like it can be closed - no confirmation and no response from the reporter. :angry:
