### ISSUE TITLE
Change appearance or background in MATE and notification daemon defaults to nodoka

### ISSUE THREAD

**Issue by arehtykitna** [mate-desktop/mate-notification-daemon#42]
I use Slider as the theme for notifications. However whenever I make a change to the appearance options or switch to another desktop background, the notification-daemon theme reverts to nodoka. I change the setting back manually each time using dconf editor. seems the only way to make it stick right now.

Not completely fubar by any means. Just a minor annoyance I would appreciate you looking into.

OS details:

Fedora 21 MATE-Compiz Spin 32-bit (same happened with Fedora 20 but I believe it is upstream and not anything to do with Fedora Project)
notification-daemon: * 2014-10-23 Wolfgang Ulbrich <chat-to-me@raveit.de> - 1.8.1-1
mate-desktop: 1.8.1-9
mate-settings-daemon - 1.8.2-1

If you need any further info please ask. not sure what is needed. Thank you! Wolfgang is the package maintainer for Fedora Project's MATE-Compiz desktop environment.

**Comment by NiceandGently** [comment]
Imo, hardcoding that with the index.theme file is not a nice solution.
Because we have 3 different notification themes + the one from the theme itself.
And you never know which theme is prefered by the user.

**Comment by infirit** [comment]
There is now a checkbox like we have for the background that allows to save save the notification theme. It is off by default. https://github.com/mate-desktop/mate-control-center/commit/90f97916e28326bcc4481a7cef72705ee359d361
