### ISSUE TITLE
"default-sound" key from org.mate.NotificationDaemon is not used by daemon or capplet

### ISSUE THREAD

**Issue by monsta** [mate-desktop/mate-notification-daemon#48]
We have that key in schema and in daemon.h, but it's not really used anywhere.
Should it be deleted, or should some code using it be added to daemon and/or capplet?

**Comment by NiceandGently** [comment]
+1 for deleting,
If it not used nobody will missed it.

**Comment by infirit** [comment]
Go ahead and delete it.
