### ISSUE TITLE
daemon does not listen to some GSettings keys, only reads them once

### ISSUE THREAD

**Issue by monsta** [mate-desktop/mate-notification-daemon#49]
There are some keys in org.mate.NotificationDaemon schema that are only read by the daemon once. It does not connect to GSettings to listen to any changes in these keys. So if you change the values of these keys while the daemon is running, you'll have to restart the daemon in order for the changes to take effect.

I think this should be corrected.

The keys are:
- sound-enabled
- monitor-number
- use-active-monitor

**Comment by GiedriusS** [comment]
Are you sure? In notify_daemon_notify_handler() we read GSETTINGS_KEY_SOUND_ENABLED each time a notification is shown in

**Comment by GiedriusS** [comment]
Before showing each notification each of these settings are read thus it does "listen" to changes on a per notification basis. Since my PR regarding "sound-enabled" wasn't pulled I think this should be closed.

**Comment by monsta** [comment]
Sure - when I wrote this, I didn't even think about how daemon is really activated :smile:
