### ISSUE TITLE
mate-notification-daemon killed by SIGTRAP gtk_widget_get_realized

### ISSUE THREAD

**Issue by samtygier** [mate-desktop/mate-notification-daemon#55]
Occurred in fedora 22. Forwarded from https://bugzilla.redhat.com/show_bug.cgi?id=1224782

Description of problem:
Played a song in rhythmbox

Version-Release number of selected component:
mate-notification-daemon-1.10.0-1.fc22

Additional info:
reporter:       libreport-2.5.1
backtrace_rating: 4
cmdline:        /usr/libexec/mate-notification-daemon
crash_function: _g_log_abort
executable:     /usr/libexec/mate-notification-daemon
global_pid:     26578
kernel:         4.0.4-301.fc22.x86_64
runlevel:       N 5
type:           CCpp
uid:            1000
var_log_messages: [System Logs]:\n-- Logs begin at Mon 2015-05-18 08:44:34 BST, end at Mon 2015-05-25 18:18:06 BST. --

Truncated backtrace:
```
Thread no. 1 (10 frames)
 #0 _g_log_abort at gmessages.c:315
 #3 g_return_if_fail_warning at gmessages.c:1088
 #4 gtk_widget_get_realized at gtkwidget.c:6076
 #5 gtk_widget_dispose at gtkwidget.c:8797
 #7 gtk_box_forall at gtkbox.c:1251
 #8 notify_daemon_notify_handler at daemon.c:1365
 #9 dbus_glib_marshal_notification_daemon_VOID__STRING_UINT_STRING_STRING_STRING_BOXED_BOXED_INT_POINTER at notificationdaemon-dbus-glue.h:102
 #10 invoke_object_method at dbus-gobject.c:1906
 #11 object_registration_message at dbus-gobject.c:2168
 #12 _dbus_object_tree_dispatch_and_unlock at dbus-object-tree.c:1018```

**Comment by NiceandGently** [comment]
another downstream report
https://bugzilla.redhat.com/show_bug.cgi?id=1243330

**Comment by monsta** [comment]
Confirmed, reproduced in Debian Jessie. Notifications from rhythmbox kill m-n-d.
