### ISSUE TITLE
mate-notification-daemon shouldn't exit with return 1 on idle.

### ISSUE THREAD

**Issue by elkrejzi** [mate-desktop/mate-notification-daemon#56]
I have been trying kdbus lately and it occoured to me that mate-notification-daemon will exit with error-code 1, which then kdbus registers as failure. All services that exit cleanly should exit(0) or return(0) anyways.

See also:

https://github.com/systemd/systemd/issues/313

**Comment by GiedriusS** [comment]
Could you link to some DBus documentation where it talks about exit codes? Particularly about this. I can't find anything myself

**Comment by elkrejzi** [comment]
Well, isn't it a rule (or a convention) that every non-zero exit status means error? (Not really related to D-Bus, but I don't think it's an exception).

**Comment by GiedriusS** [comment]
Yeah, from POSIX: "A value of zero (or EXIT_SUCCESS, which is required to be zero) for the argument status conventionally indicates successful termination.". Was just wondering if exit status tracking is actually in some official D-Bus document. Well, I think we could change it to EXIT_SUCCESS if some daemon cares about that... I don't see what bad could happen.
