### ISSUE TITLE
GTK3: standard theme crashed when clicking on close button

### ISSUE THREAD

**Issue by NiceandGently** [mate-desktop/mate-notification-daemon#69]
Clicking on close button with standard theme crashed m-n-d.
build is from git master  20150728.c47626f
mate-notification-daemon-1.10.2-10.5.git20150728.c47626f.fc22.x86_64
stacktrace at: https://dl.dropboxusercontent.com/u/49862637/Mate-desktop/Bugs/m-n-d-standard-backtrace
```
#48 0x0000000000404b25 in main (argc=1, argv=0x7ffe02e5c808) at daemon.c:1799
        daemon = 0x1c6a0c0 [NotifyDaemon]
        connection = <optimized out>
        bus_proxy = <optimized out>
        error = 0x0
        res = <optimized out>
        request_name_result = 1
```

**Comment by NiceandGently** [comment]
confirmed, issue is fixed.
Thank you

**Comment by NiceandGently** [comment]
m-n-d GTk2 build from latest 1.10 git has the the same problem.
mate-notification-daemon-1.10.2-0.2.git20150724.f9aedaf.fc22
Clicking on close button in standard theme crashed m-n-d too, btw. i get a abrt alarm.
Stacktrace looks similar.
https://dl.dropboxusercontent.com/u/49862637/Mate-desktop/Bugs/m-n-d-gtk2standard-stacktrace

**Comment by NiceandGently** [comment]
And the fix is good for gtk2 too.

**Comment by infirit** [comment]
Pushed to 1.10
