### ISSUE TITLE
GTK3 slider: invisible text

### ISSUE THREAD

**Issue by City-busz** [mate-desktop/mate-notification-daemon#90]
The notification bubble does not show any text. I tested with multiple GTK+ themes.

Package versions:
- gtk3 3.18.5
- mate-notification-daemon (gtk3) 1.12.0

**Comment by raveit65** [comment]
This is complete weird, i notice this too in VM's
but on my main box with nvidia graphic i see the correct bg/fg color from gtk theme.
All with the same package.

**Comment by monsta** [comment]
It somewhat works here... but the colors are surely not right :smile:

![slider-notification](https://cloud.githubusercontent.com/assets/5138986/11368509/4a29236a-92cb-11e5-97bf-8b6d5e870a41.png)

![slider-notification-with-buttons](https://cloud.githubusercontent.com/assets/5138986/11368513/4e80c774-92cb-11e5-8aba-944b6748c28f.png)

This is in GTK+2 MATE desktop with GTK+3 build of m-n-d.
LMDE 2 based on Debian Stable, GTK+ 3.14, real hardware with nvidia card.

**Comment by City-busz** [comment]
I created pull request https://github.com/mate-desktop/mate-notification-daemon/pull/92, which fixes an uninitialized variable, and makes the text visible, but it's still hard to read, and I have no idea why.

**Comment by monsta** [comment]
Cool, it made text on buttons (see second screenshot above) black. Much better.

**Comment by monsta** [comment]
But yes, in my GTK+3 VM text is almost-black on black... barely readable :confused:

**Comment by raveit65** [comment]
> But yes, in my GTK+3 VM text is almost-black on black... barely readable :confused:

I'm confused why it works well in f22 VM with gtk+-3.16, but not in f23 VM with 3.18.
Maybe this is the reason why it works on bare metal installation with f22.
I don't have a Mate gtk3 installation on bare metal with buggy gtk+-3.18 to confirm that.

**Comment by raveit65** [comment]
well, i've create an branch to work on slider.
Here, https://github.com/mate-desktop/mate-notification-daemon/commit/076f608 is reverted.
Unfortunately the result is black fg on black fg, and the bg looks more than coco theme bg.
![notification-slider-revert](https://cloud.githubusercontent.com/assets/961604/11794072/b859a410-a2af-11e5-87b4-ab48f17fcdff.png)

**Comment by monsta** [comment]
Weird, your theme is dark but font color in notification isn't white as it should be...

**Comment by monsta** [comment]
If I comment out the call of ```override_style``` in ```on_style_updated``` function, background is drawn as it should (from current GTK+ theme). Unfortunately, there are some visual issues (try changing GTK+ theme from dark to light or vice versa to see).

**Comment by raveit65** [comment]
This screenshot was with blue-submarine gtk theme which has a light blue bg.
Same result with Menta.

**Comment by raveit65** [comment]
Hmm, commenting out this line in dev-slider branch doen't change anything.
```
#if GTK_CHECK_VERSION (3, 0, 0)
static void on_style_updated(GtkWidget* widget, WindowData* windata)
{
	g_signal_handlers_block_by_func(G_OBJECT(widget), on_style_updated, windata);
/*	override_style(widget);*/

	gtk_widget_queue_draw(widget);

	g_signal_handlers_unblock_by_func(G_OBJECT(widget), on_style_updated, windata);
}
#else
```

**Comment by monsta** [comment]
@City-busz: well, ```color_reverse``` function seems to be the culprit... if I comment out both calls to it, all is fine (unless I start switching between light and dark GTK+ themes though).

Interesting that in GTK+2 build ```color_reverse``` works as described: it indeed reverts the colors, so I get gray-on-black notification when I use Menta, and black-on-gray one when I use BlackMATE. It seems like it was so since Slider was created in 2010.

Do we really need this? What do you think?
Because I'm not really sure anyone would want a notification appearing with colors inverted (in regard to one's selected GTK+ theme)...

**Comment by monsta** [comment]
And apparently, ```color_reverse``` does not work for some reason on my machine with GTK+3 build of m-n-d and GTK+ 3.14 (as on screenshots above). Colors aren't inverted for my Mint-X theme which is light one.

**Comment by raveit65** [comment]
OK, using this works fine with gtk+-3.18.x
```
static void override_style(GtkWidget* widget)
{
	GtkStyleContext *context;
	GtkStateType state;
	GdkRGBA fg;
	GdkRGBA bg;
	GdkRGBA fg2;
	GdkRGBA bg2;

	context = gtk_widget_get_style_context (widget);

	state = (GtkStateType) 0;
	while (state <= GTK_STATE_FOCUSED)
	{
		GtkStateFlags flags;
		flags = state_flags_from_type (state);

		gtk_style_context_get_color (context, flags, &fg);
		gtk_style_context_get_background_color (context, flags, &bg);

		fg2 = fg;//color_reverse(&fg, &fg2);
		bg2 = bg;//color_reverse(&bg, &bg2);

		gtk_widget_override_color (widget, flags, &fg2);
		gtk_widget_override_background_color (widget, flags, &bg2);

		state++;
	}
}
```

**Comment by City-busz** [comment]
I found the problem: the gtk_widget_override_* functions are called multiple times on each elements, and it messes up the colors. They should be called only once on the toplevel element. Pull request https://github.com/mate-desktop/mate-notification-daemon/pull/93 fixes the problem I think.

**Comment by monsta** [comment]
You mean with ```color_reverse``` still enabled?

**Comment by City-busz** [comment]
Yes, now everything should be the same as the gtk2 version.

**Comment by monsta** [comment]
Cool, seems to work fine. I wonder if we need ```style-set``` signal on multiple elements in GTK+2?

**Comment by raveit65** [comment]
For some reason fg color is black if  i use the patch on top of https://github.com/mate-desktop/mate-notification-daemon/commit/6645e6f

**Comment by raveit65** [comment]
With gtk+-3.16 i see the bg color from gtk theme, if using the patch on top of latest commit.

**Comment by monsta** [comment]
@City-busz: hmm, I just noticed I get different results with 3.14 and 3.18...

3.14:
- Menta: colors are not reversed - notification is black-on-gray;
- BlackMATE: colors are not reversed notification is white-on-black.

3.18:
- Menta: colors are reversed - notification is gray-on-black;
- BlackMATE: color reversing goes wrong - notification is white-on-gray but should be black-on-white.

**Comment by City-busz** [comment]
Oh, it makes really difficult that it works very differently between GTK+ versions... Probably the easiest way to solve this is to not reverse colors at all.

**Comment by monsta** [comment]
Yes, and we're ready to switch m-n-d to GTK+3 only, so users with different GTK+3 will get different results...

My only concern here is that removing color reversing might be a surprise for some people who're used to it in GTK+2 build :smile:

**Comment by raveit65** [comment]
fixed for all gtk+ versions.
https://github.com/City-busz/mate-notification-daemon/commit/d1eaf938f5e4da182225bf4ca93b7de81f4803d6
https://github.com/mate-desktop/mate-notification-daemon/commit/d80ac825a8815317e06d206c2199bedfe0474f85
