### ISSUE TITLE
GTK3: line wrap does not work for notification text

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/mate-notification-daemon#94]
![m-n-d](https://cloud.githubusercontent.com/assets/961604/11843171/6450e946-a408-11e5-813c-f9d763c1a2c7.png)

**Comment by raveit65** [comment]
Btw, this is independent from the notification theme.

**Comment by monsta** [comment]
Interesting - while testing this I've found out that issue mentioned in https://github.com/mate-desktop/mate-notification-daemon/pull/52 is still reproducible on my machine :confused:

**Comment by raveit65** [comment]
fixed
https://github.com/mate-desktop/mate-notification-daemon/commit/6f0ef78612d344d71acd75cc31cdf3ae008f5adf
