### ISSUE TITLE
GTK3 sound/battery icons not themable

### ISSUE THREAD

**Issue by sanderboom** [mate-desktop/mate-notification-daemon#96]
Quite a shot-in-the-dark, so excuse me if this is the wrong place to report this.

While testing mate-GTK3 it seems that the sound- and battery indicators never follow the theme.

![image](https://cloud.githubusercontent.com/assets/5956570/12387580/e36c04e8-bdcd-11e5-8526-91b820e3bb28.png)

Other theme:
![image](https://cloud.githubusercontent.com/assets/5956570/12387602/f6c71622-bdcd-11e5-8d7e-501cff5f418c.png)

Thanks!

**Comment by raveit65** [comment]
This is the wrong place!
Looks like a issue with your theme.

**Comment by sanderboom** [comment]
OK. I tested with 2 themes, but will give it an other shot.
